In [ ]:
# Lab05 - Task 01
# Write a Python program to find the maximum and minimum value of a given flattened array.

print("==== Max & Min of Flattened Array ====\n")

import numpy as np

# Original 2D array
array = np.array([[0, 1], [2, 3]])
print("Original flattened array:")
print(array)

# Flatten the array using ravel()
flat_array = np.ravel(array)

# Find maximum and minimum using NumPy functions
max_value = np.max(flat_array)
min_value = np.min(flat_array)

print("\nMaximum value of the above flattened array:", max_value)
print("Minimum value of the above flattened array:", min_value)

==== Max & Min of Flattened Array ====

Original flattened array:
[[0 1]
 [2 3]]

Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [ ]:
# Lab05 - Task 02
# Create a 3x3 matrix with values ranging from 2 to 10.

print("==== 3x3 Matrix with Values from 2 to 10 ====\n")

import numpy as np

# Create a 3x3 matrix with values from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

==== 3x3 Matrix with Values from 2 to 10 ====

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [7]:
# Lab05 - Task 03
# Write a NumPy program to convert an array to a float type.

print("==== Convert Array to Float Type ====\n")

import numpy as np

# Original array
array = np.array([1, 2, 3, 4])
print("Original array:", array)

# Convert array to float type
float_array = array.astype(float)
print("Array converted to a float type:", float_array)

==== Convert Array to Float Type ====

Original array: [1 2 3 4]
Array converted to a float type: [1. 2. 3. 4.]


In [8]:
# Lab05 - Task 04
# Multiply 2x2 matrices and take the transpose of the resultant matrix.

print("==== Matrix Multiplication and Transpose ====\n")

import numpy as np

# Define the matrices
M1 = np.array([[5, 5], [1, 2]])
M2 = np.array([[0, 1], [1, 0]])

# Multiply the matrices
result = np.dot(M1, M2)
print("Result of M1 x M2:\n", result)

# Take the transpose of the result
transpose_result = np.transpose(result)
print("\nTranspose of the resultant matrix:\n", transpose_result)


==== Matrix Multiplication and Transpose ====

Result of M1 x M2:
 [[5 5]
 [2 1]]

Transpose of the resultant matrix:
 [[5 2]
 [5 1]]


In [10]:
import numpy as np

# Define the matrix
matrix = np.array([
    [6, 1, 1, 3],
    [4, -2, 5, 1],
    [2, 8, 7, 6],
    [3, 1, 9, 7]
])

# Find the inverse
inverse_matrix = np.linalg.inv(matrix)

# Print the result
print("Inverse of the matrix:\n", inverse_matrix)


Inverse of the matrix:
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
